# Generated by Django 3.2.5 on 2021-10-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='item code')),
                ('name', models.CharField(max_length=64, verbose_name='item name')),
                ('category', models.CharField(max_length=64)),
                ('price', models.IntegerField(verbose_name='item price')),
                ('quantity_available', models.IntegerField(verbose_name='quantity available')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='phone number')),
                ('name', models.CharField(max_length=64, verbose_name='user name')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity purchased')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date of purchase')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item', verbose_name='Item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'sales',
                'verbose_name_plural': 'sales',
            },
        ),
    ]
